# https://www.appveyor.com/docs/appveyor-yml

build_script:
  - cd "Sigman IDML"

test: off

skip_tags: true

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')
