# https://www.appveyor.com/docs/appveyor-yml

install:
  - ps: Start-FileDownload 'ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn-x64.zip'
  - 7z x zip300xn-x64.zip -ozip300xn-x64
  - cd zip300xn-x64
  - 7z x zip300xn-x64.zip -ozip300xn-x64
  - move zip300xn-x64 "%ProgramFiles%"
  - set PATH=%PATH%;%ProgramFiles%\zip300xn-x64
  - cd ..

build_script:
  - cd "Sigman IDML"
  - zip -X0 ..\Sigman.idml mimetype
  - zip --recurse-paths --no-dir-entries -X9 ..\Sigman.idml * --exclude mimetype

test: off

artifacts:
  - path: Sigman.idml

skip_tags: true

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
