# https://www.appveyor.com/docs/appveyor-yml

install:
  - ps: (New-Object Net.WebClient).DownloadFile('ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn-x64.zip', [IO.Path]::Combine($env:APPVEYOR_BUILD_FOLDER, 'zip300xn-x64.zip'))
  - 7z x zip300xn-x64.zip -ozip300xn-x64
  - cd zip300xn-x64
  - 7z x zip300xn-x64.zip -o"%ProgramFiles%\zip300xn-x64"
  - set PATH=%PATH%;%ProgramFiles%\zip300xn-x64
  - cd ..

build_script:
  - cd "Envelope IDML"
  - zip -X0 ..\Envelope.idml mimetype
  - zip --recurse-paths --no-dir-entries -X9 ..\Envelope.idml * --exclude mimetype
  - cd "..\Sigman IDML"
  - zip -X0 ..\Sigman.idml mimetype
  - zip --recurse-paths --no-dir-entries -X9 ..\Sigman.idml * --exclude mimetype

test: off

artifacts:
  - path: Envelope.idml
  - path: Sigman.idml

skip_tags: true
